### ISSUE TITLE
consider splitting `lib.rs` into multiple files...

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/pyo3_branchwater#62]
it's getting a bit unwieldy!

**Comment by ctb** [comment]
@luizirber curious if you have any hot takes on #64. What's a good way to break up the code??

**Comment by luizirber** [comment]
I think it depends on how you navigate the code while developing. While there are many functions, conceptually they are all working somewhat together, so even being on `lib.rs` doesn't seem like a bad approach to me at the moment (because it is also easy to search the code).

[In sourmash](https://github.com/sourmash-bio/sourmash/tree/d0e3726814749b43e3b0d1d9c0e3b3bb47d045af/src/core/src) I tried to go with "entrypoints" for higher-level concepts, and then expanding into a module/dir if it grew too much (`ffi`, `index`, and `sketch` are examples of that). But branchwater doesn't have that many entrypoints...

#64 looks good. `utils` tends to turn into a grab-bag, but the alternative would be to keep in `lib.rs`, which... doesn't help making it smaller =P

**Comment by ctb** [comment]
> I think it depends on how you navigate the code while developing. While there are many functions, conceptually they are all working somewhat together, so even being on `lib.rs` doesn't seem like a bad approach to me at the moment (because it is also easy to search the code).

I have no idea how I navigate the code while developing in Rust 😆 . It's one of the frustrating things about learning a new language!

I have immense trouble navigating the sourmash `src/core` code. I usually end up using `git grep`. Are there better approaches? Does vs code help here, or something else?

> #64 looks good. `utils` tends to turn into a grab-bag, but the alternative would be to keep in `lib.rs`, which... doesn't help making it smaller =P
> (but it is also arguable that they are useful functionality that should in in sourmash `core`, so hopefully `utils` goes away over time =])

yes, I agree that `utils` could/should go away over time!

I do think it's nice to have the top-level functions being exported to pyo3 placed in their own files; they are each individual & custom, after all! this should really help with decluttering the code and reviewing PRs IMO.

---

random different question: are you using rayon in sourmash-rs core? I am wondering if a possible boundary is that sourmash-rs core will be threadsafe (like, you know, rust in general) but then any particular parallelization will be done elsewhere?
